### ISSUE TITLE
Reset button bug

### ISSUE THREAD

**Issue by ghost** [CyberSphinxxx/TypeGlow#1]
The reset button isn't working when the level is already completed.

**Comment by CyberSphinxxx** [comment]
Hi @riezane,

Thank you for bringing this issue to my attention! I’m pleased to inform you that the bug with the reset button has been patched in the latest release (v1.2.3). You can find the update here: [TypeGlow v1.2.3 Release](https://github.com/CyberSphinxxx/TypeGlow/releases/tag/v1.2.3).

I appreciate your feedback, and please don’t hesitate to reach out if you encounter any more issues or have further suggestions!
